### ISSUE TITLE
compatibility between sinricpro and other webserver application

### ISSUE THREAD

**Issue by robademar** [sinricpro/sinricpro-website#7]
I'm trying to integrate blind example into my program with the remote program loading  requiring a dedicate port, i my case I use 81 or 88 for it.
I did use the working blind example and I copied it into my program, same device,app and secret key.
I enabled the debug function and I see the following:

Connecting....
Connected to Vodafone-roberto
IP address: 192.168.1.155
mDNS responder started
inizio set up sinric
[SinricPro]: Device "5ebda5633045f14787e3fe33" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "5ebda5633045f14787e3fe33".
collegata al wifi 
[SinricPro:Websocket]: Connecting to WebSocket Server (ws.sinric.pro)
[SinricPro:Websocket]: headers: 
appkey:778515ea-5f02-41d9-a22c-390a6f8b0ed7
deviceids:5ebda5633045f14787e3fe33
restoredevicestates:false
platform:ESP32
version:2.4.0

device is not online for sinric web site.

Question is : is there a compatibility issue between web server coding?

**Comment by kakopappa** [comment]
"5ebda5633045f14787e3fe33" does not exist. Creating new device

Is your device id correct?

**Comment by robademar** [comment]
ArunaI've seen that but what convinced me that something is wrong in my code is the debug log of the example, where I just inserted my credential vlues. It is different from mine just after the version 2.4.0 message.This is the debug of the example:
[SinricPro]: Device "5ebda5633045f14787e3fe33" does not exist. Creating new device
[SinricPro:add()]: Adding device with id "5ebda5633045f14787e3fe33".
[SinricPro:Websocket]: Connecting to WebSocket Server (ws.sinric.pro)
[SinricPro:Websocket]: headers: 
appkey:778515ea-5f02-41d9-a22c-390a6f8b0ed7
deviceids:5ebda5633045f14787e3fe33
restoredevicestates:false
platform:ESP32
version:2.4.0
[SinricPro:Websocket]: connected
Connected to SinricPro
[SinricPro:Websocket]: receiving data
[SinricPro.handleReceiveQueue()]: 1 message(s) in receiveQueue
[SinricPro.handleReceiveQueue()]: Signature is valid. Processing message...
[SinricPro:extractTimestamp(): Got Timestamp 1589562754

and the example works!I will try to create a new device and I'll let you know.thanks and ciaoGiovanni Roberto Mariani 

    Il sabato 16 maggio 2020, 03:36:14 CEST, Aruna Tennakoon <notifications@github.com> ha scritto:  
 
 

"5ebda5633045f14787e3fe33" does not exist. Creating new device

Is your device id correct?

**Comment by robademar** [comment]
I had a further test and I used fixed ip address because I want to find the device always at the place in my network.
I used this mask 
WebServer server(88);
IPAddress gateway(192, 168, 1, 1);
IPAddress subnet(255, 255, 255, 0);
IPAddress local_IP(192, 168, 1, 155);

Well removing the fix addressing it works, both sinric and remote loading.
